# Generated by Django 3.2.12 on 2022-05-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
