# Generated by Django 3.2.12 on 2022-05-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='page_date',
        ),
    ]
