# Generated by Django 3.2.12 on 2022-05-08 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220508_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='page_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
